server.port: 0
spring:
        application.name: rest-application
        main.banner-mode: "off"
        cloud.config:
                discovery:
                        enabled: true
                        serviceId: config-server

eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:7001/eureka/
                registryFetchIntervalSeconds: 1
                instance:
                        leaseRenewalIntervalInSeconds: 1
