server:
        port: 7001
spring:
        application.name: discovery-server
        main.banner-mode: "off"

eureka:
        instance:
                leaseRenewalIntervalInSeconds: 2
                leaseExpirationDurationInSeconds: 2
                hostname: localhost
        server:
                evictionIntervalTimerInMs: 2000
                response-cache-update-interval-ms: 2000
        client:
                serviceUrl:
                        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
                registerWithEureka: false
                fetchRegistry: false
